closure_body_length:
  warning: 30
  error: 60

excluded:
  - Pods
  - LeaveSchedule/Vendors

file_length:
  warning: 500
  error: 600

function_parameter_count: 7

identifier_name:
  min_length: 1
  max_length: 30

line_length:
  warning: 200
  error: 220

number_separator:
  minimum_length: 5
  minimum_fraction_length: 7

opt_in_rules:
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiple_closures_with_trailing_closure
  - number_separator
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

disabled_rules:
  - todo

type_body_length:
  warning: 300
  error: 400
