platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!

target 'GitHubViewer' do
  pod 'Alamofire', '5.0.2'
  pod 'NotificationBannerSwift', '3.0.2'
  pod 'SwiftLint', '0.39.1'
  pod 'SnapKit', '5.0.1'
  pod 'KeychainAccess', '4.2.0'
  pod 'AlamofireImage'
end
